server:
  port: 8090

# 沙盒测试参数
alipay:
  # 应用id
  app_id: 2021000121606939
  # 应用私钥
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDSK8AdJ9bZZmDm3j4M8VAvLfd+pU1OOQ0BxRW7TX4Z7RMaZLbxGoSAQsJ2NjFPoV+eyv5PHfYgfjcWGpSHkWqS8IMu1voTYpFnFLfMQPcmr+SjDJIWqpOVfYxBgSqXy/0MLyHoOWPB170vmER5oqmsQgfu2/B9TTyzpoH6gmaBYvSfRDWPAieSf325f0A/XcYF+ihA96t5rbXfEY5dchXTvu8WZ8GNT916lLkXmHq0bj6j4w1XoQit2GdZygU16L+FVdqrKyPJ6E470oc/gnqd6gTWj9jjfa1c/PwHQjA7DUw8fe+97+Yi8cyefDyOggc7GXCQdWoyIjgEG02gH1ptAgMBAAECggEBAMVtObNpqCZiSKa2oD1SNcuL95CtQTg42WIPPAHNoqZCEI7biwpjqZI+pCOddqbh5UvqTggOEhWl2qNV5q6OyDkt210VrqalEgdt69XgNQrPcgxEE7tdEvP7ktQ5vMQJaDSY1dYqiu4ddecOt0w3pAFfqcoUKw3ZjysHP9QNyLLCiG3t9r4EqBFAgva+QiWtmmcGKpgOyyfglHVu+Q8bvfO/OcFoRmcP3++d2MJp4jsU3M78wSy8t5Q8h1inY5CfnFDtC8pWAbmUY4q5nHJbpbXqNipEDvsi1Yye/UZ9GaBi4eh88bw1Nk2u5K91pixzNeiq3BBZnOfh3LxDUlnSMnUCgYEA91oT3yM59vEZVwkxU0FJxvL9vIRmogSsocjJV8/FiE9kJtz8YM7AvyPthCunURlFBEZ/Fwbd6F1eSaE4C8F6k4HWGAhL/WWamOQBzRZh1tTZXrBryOtUyFGKChIIPrVlruJQwNFpTwzuVLHXJJJiiWPjkuMhsmEiMtevOCuyTGMCgYEA2YTieVfFOHYETN+pryZfnICRhRBp6yTkBMFTSwQqtEQ9lZXljQANQfYBgOj8qFxepHDJa764wQax8p53GjGBWbc826BSzkDZW4KIiaQo87gIZPX5TzeJrWEXi5PaYU8Ll6qP4F9JsoxRS2D2/VZ5T2z+roMkWWuERyHzhcmi7u8CgYA6Fd8gwUb1ZHzM4Y3BvU0z+Q/42ya22V4ox9vwUQxUDEC6l550pVjCCg/Wv+GUu9hnPp7Nq4Ek9fgUVlWw/Qhp5019a0VdBiUdzj1WCfGD34wEHm3RSuIoAG3oG3/wKezs+px4CzUtqR22qeSZ4/5bwSdJ8SiSmRjM07WD/U7rfQKBgQDMfROX9b6P7MrwJhhUc6PQ8kFbsemRSRYfrkuKq3kmDT1EIi4yVwkfqJETSnU0JdpHh0ykQSFZPd0OdJENi9rJp+zLoDYYdniggd+wXiatsKYbm+5r3Y9N8of7DN1xO6lvRMaLrakP9L/8OEUaNzBGTfZDwz/p3Jz3bmCMttm4+wKBgG75+qrPw32jbegwWG7cpKKGNAgD5wbeud+pObkBan8hiR4XAI1IkkFaeIBeRb2zRBB3pQ7baI9UPudKT8OK6Foz2ujg5p1uQZe6Vy0ieDaHr6vfbn1PDx8QvPuSia/C2NT61hlV+wDvRJeyPFSiN4V49W3B5R+uYvNBOoxYaccA
  # 支付宝公钥
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjoSnMHCkIC4TI9NiGjLdzhihO1muECr9AwpVpTJHfYiQ0aWFu++FdNbR6XDDqVNA3D7f42X6dN2Zm9x3PcYCgYJvd8rUy2fjhR4dsSR7Ids3YfvjQ5billKKyR55fddrk+CNGzRTrXyQIBZ2uaTZI8aMtDY94B6TLCJ7zMXsEK3NgUppbrzTPUwFJiPW6VPJW0YPWMRM5jpCyXPa1vo7rUvuFVNg6J0R1clZJK5ZrQnMjDG3YIvwiATcbZlPhqOHJ3l90Ex4Y3GDrKDA4jfF04pWWTBknqeOWsD6WcmhtddsAhi9Ls2M1JtABJCJbSx9y2IR5OlYWrGUert44AevMQIDAQAB
  # 服务器异步通知页面路径（必须能公网访问）
  notify_ur1: http://net.fs233.cc/api/alipay/notifyurl
  # 页面跳转同步通知页面路径
  return_ur1: http://net.fs233.cc/returnurl
  # 签名方式
  sign_type: RSA2
  # 编码方式
  charset: utf-8
  # 支付宝网关
  gatewayUrl: https://openapi.alipaydev.com/gateway.do



